### PR TITLE
Converters

### PR DESCRIPTION
**Pull request by bnorthan**
Add converters based on @hinerm's Matlab converters.

### CODE REVIEW

**Comment by ctrueden** [comment]
Can we drop the "Simple" from various class names? Are we really going to implement a non-Simple-ITK-based ITK integration later, which coexists with the SimpleITK one?

**Comment by thewtex** [comment]
I think a non-Simple version is a possibility. The Simple description avoids confusion, too.

**Comment by bnorthan** [comment]
@ctrueden, [SimpleITK](http://www.simpleitk.org/) provides a 'easy to use procedural interface' into ITK.  So the interfaces are actually different than ITK.  As @thewtex  mentioned, it is possible to wrap regular ITK components with JNI (or use SWIG) and have them co-exist with simple ITK.  So I suggest we go back to SimpleITK (but make sure the capitalization is right).

**Comment by thewtex** [comment]
+1

**Comment by ctrueden** [comment]
As you wish! See https://github.com/imagej/imagej-itk/pull/10

**Pull request merged**
